Experiments directory with Stylus and OCR results of research
jlopez8/math_notes pull request #2
Opened 2021-05-16 02:38 UTC by jlopez8

This branch is solely to merge two minor notebooks reflecting the recent findings we talked about: using a stylus/mouse to ingest in a jupyter notebook and the original OCR research tool phase.

2021-05-16 02:43 UTC, rkingery commented
You're still keeping bad style with your folder/file names. Again, no spaces, and keep everything lower case, with words connected by hyphens or underscores (consistently across the repo, pick one). And use shorter file names for things (never more than 20 characters). I think your long, spaced file names are what's causing github not to render your notebooks. Do fix these first.

2021-05-16 02:45 UTC, rkingery requested changes
See comments.

2021-05-19 15:34 UTC, jlopez8 commented
I removed my blocker related to Git. I prematurely (?) squashed my commits, which I realize now you may have wanted more input before I did that. Other than that, I’m ready to merge, but am waiting to make sure everything is okay.

2021-05-20 01:20 UTC, rkingery approved these changes

2021-05-20 01:23 UTC, merged